var imageElement = document.getElementById("image")
var questionElement = document.getElementById("question")
var infoElement = document.getElementById("info")
var buttons = [
    document.getElementById("no"),
    document.getElementById("yes"),
    document.getElementById("next")
]
var scoreElement = document.getElementById("score")
var answer = false
var numCorrect = 0
nextQuestion()

function nextQuestion() {
    // Reset styling
    imageElement.src = "blank.jpg"
    buttons[+answer].className = buttons[+answer].className.replace("success", "secondary")
    buttons[+!answer].className = buttons[+!answer].className.replace("danger", "secondary")
    buttons[2].hidden = true
    questionElement.hidden = false
    infoElement.hidden = true

    // Prepare question
    if(Math.random() > 0.5) {
        setGANImage()
    }else {
        setFFHQImage()
    }
}

function setGANImage() {
    answer = false
    infoElement.innerText = "This image was generated by StyleGAN2"
    imageElement.src = "https://thispersondoesnotexist.com/image?"+Math.round(Math.random() * 1000)
}

function setFFHQImage() {
    answer = true
    infoElement.innerText = "This image was taken from the FFHQ dataset"
    imageElement.src = "https://thispersondoesnotexist.com/image?"+Math.round(Math.random() * 1000)
}

function checkAnswer(exists) {
    buttons[+answer].className = buttons[+answer].className.replace("secondary", "success")
    buttons[+!answer].className = buttons[+!answer].className.replace("secondary", "danger")
    buttons[2].hidden = false
    questionElement.hidden = true
    infoElement.hidden = false
    if(exists == answer) {
        numCorrect++
        scoreElement.innerText = numCorrect
    }
}