var imageElement = document.getElementById("image")
var blankElement = document.getElementById("blank")
var questionElement = document.getElementById("question")
var infoElement = document.getElementById("info")
var buttons = [
    document.getElementById("no"),
    document.getElementById("yes"),
    document.getElementById("next")
]
var scoreElement = document.getElementById("score")
var answer = false
var answered = false
var numCorrect = 0
var numTotal = 0
nextQuestion()

function nextQuestion() {
    // Reset styling
    imageElement.src = "blank.jpg"
    buttons[+answer].className = buttons[+answer].className.replace("success", "secondary")
    buttons[+!answer].className = buttons[+!answer].className.replace("danger", "secondary")
    buttons[2].hidden = true
    infoElement.hidden = true
    questionElement.innerText = "Does this person exist?"

    // Prepare question
    answered = false
    imageElement.hidden = true
    blankElement.hidden = false
    if(Math.random() > 0.5) {
        setGANImage()
    }else {
        setFFHQImage()
    }
    setTimeout(() => {
        imageElement.hidden = false
        blankElement.hidden = true
    }, 1500)
}

function setGANImage() {
    answer = false
    infoElement.innerHTML = "This image was generated by NVIDIA's generative algorithm, <a target='blank' href='https://github.com/NVlabs/stylegan2'>StyleGAN2</a>."
    imageElement.src = "https://thispersondoesnotexist.com/image?"+Math.round(Math.random() * 1000)
}

function setFFHQImage() {
    answer = true
    var index = 10000 + Math.round(Math.random() * 3000)
    var metadata = window.FFHQMetadata[index]
    infoElement.innerHTML = "This image was taken from the <a target='blank' href='https://github.com/NVlabs/ffhq-dataset'>FFHQ dataset</a> that was used to train StyleGAN2. It was posted by <a target='blank' href='"+metadata.photo_url+"'>"+metadata.author+"</a>, licensed under <a target='blank' href='"+metadata.license_url+"'>"+metadata.license+"</a>"
    imageElement.src = "https://dtcan.dev/doesthispersonexist/ffhq/"+index+".png"
}

function checkAnswer(exists) {
    if(!answered) {
        answered = true
        buttons[+answer].className = buttons[+answer].className.replace("secondary", "success")
        buttons[+!answer].className = buttons[+!answer].className.replace("secondary", "danger")
        buttons[2].hidden = false
        infoElement.hidden = false
        questionElement.innerText = "This person "+(answer ? "does" : "does not")+" exist!"
        numTotal++
        if(exists == answer) {
            numCorrect++
        }
        scoreElement.innerText = numCorrect + " / " + numTotal
    }
}